name: blocklistsrv
services:
  db:
    # InfluxDB v3 is out but has no Docker image for multiple months now???
    image: influxdb:2-alpine
    container_name: db
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      "DOCKER_INFLUXDB_INIT_MODE": "setup"
      "DOCKER_INFLUXDB_INIT_RETENTION": "5w"
    ports:
      - 8086:8086
    env_file: ./configuration/.secrets
    volumes:
      - influxdb-storage:/var/lib/influxdb2
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    healthcheck:
      test: "curl -f localhost:3000/api/health"
      interval: 10s
      retries: 30
    ports:
      - 3000:3000
    env_file: ./configuration/.secrets
    secrets:
      - grafanaAdminPassword
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./configuration/grafana/datasource.yml:/etc/grafana/provisioning/datasources/db.yml
      - ./configuration/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./configuration/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
  web:
    build:
      dockerfile: docker/blocklistsrv/Dockerfile
      context: ../
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ../config.json:/src/config.json
      - ./configuration/.grafanaServiceCredential:/.grafanaServiceCredential
    env_file: ./configuration/.secrets
    secrets:
      - grafanaAdminPassword
    depends_on:
      db:
          condition: service_healthy
      grafana:
          condition: service_healthy

secrets:
  grafanaAdminPassword:
    file: ./configuration/.grafanaAdminPassword

volumes:
  grafana-storage: {}
  influxdb-storage: {}