apiVersion: 1

datasources:
  - name: InfluxDB-v2-Flux
    type: influxdb
    uid: "P6D64DDB364ABABC6"
    access: proxy
    url: $INFLUXDB_LOCATION
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'